# Site
name: "Spemer(Hyouk Seo)"
description: "Spemer's camping diary 🏕️"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
disqus: "Spemer"
locale: ko_KR
email: "ghsspower@gmail.com"
google-analytics: G-1CRN7Q6CQR

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  Spemer:
    name: Hyouk Seo
    site: https://spemer.com/
    avatar: assets/images/avatar.png
    bio: "I am a detail-oriented Digital Product & User Experience Designer, Problem Solver and Frontend Developer; create design based on human-centered design."
    email: ghsspower@gmail.com
    twitter: https://twitter.com/OfficialSpemer

social:
  name: Hyouk Seo(Spemer)
  links:
    - https://twitter.com/OfficialSpemer
    - https://www.facebook.com/ghsspower
    - https://www.linkedin.com/in/hyouk-seo-0b6801122/
    - https://github.com/spemer
    - https://www.instagram.com/spemer

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Spemer
      avatar: assets/images/avatar.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 50

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
